server:
  port: 8088

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autenticacao
    username: root
    password: 1234
    jpa:
      properties:
        hibernate:
          ddl-auto: none
      show-sql: true
  application:
    name: autenticacao-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/grabas/protocol/openid-connect/certs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

flyway:
  outputQueryResults: false

services:
  security:
    signing-key: Gr@b4s